# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 윤태인의 기술블로그
email: taein2370@naver.com
description:  저는 2005년 9월 10일에 태어났고, 미래에 소프트웨어 개발자가 되고 싶습니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://taein0910.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
